services:
  app:
    entrypoint:
      - sleep
      - infinity
    image: node:lts
    init: true
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    ports:
      - "0.0.0.0:3000:3000"
